controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

App\Controller\VoyageurController::statistics:
    path: '/voyageur/stats'
    methods: ['GET']