#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# Example of defining the route for search functionality in routes.yaml
app_voyage_search:
  path: /search
  controller: App\Controller\VoyageController::search
  methods: [GET]
