
app_login:
  path: /login
  controller: 'App\Controller\SecurityController::login'
  methods: ['GET', 'POST']

app_logout:
  path: /logout
  controller: 'App\Controller\SecurityController::logout'
  methods: ['GET']

app_main:
  path: /
  controller: 'App\Controller\MainController::index'
  methods: ['GET']

app_register:
  path: /register
  controller: 'App\Controller\RegistrationController::register'
  methods: ['GET', 'POST']

admin_index:
  path: /admin
  controller: 'App\Controller\Admin\MainController::index'

admin_users_index:
  path: /admin/Users
  controller: 'App\Controller\Admin\UsersController::index'