
app_login:
  path: /login
  controller: 'App\Controller\SecurityController::login'
  methods: ['GET', 'POST']

app_logout:
  path: /logout
  controller: 'App\Controller\SecurityController::logout'
  methods: ['GET']

app_main:
  path: /
  controller: 'App\Controller\MainController::index'
  methods: ['GET']

app_register:
  path: /register
  controller: 'App\Controller\RegistrationController::register'
  methods: ['GET', 'POST']

admin_index:
  path: /admin
  controller: 'App\Controller\Admin\MainController::index'

admin_users_index:
  path: /admin/Users
  controller: 'App\Controller\Admin\UsersController::index'


admin_users_new:
  path: /admin/Users/new
  controller: 'App\Controller\Admin\UsersController::new'
  methods: ['GET', 'POST']

admin_users_edit:
  path: /admin/Users/{id}/edit
  controller: 'App\Controller\Admin\UsersController::edit'
  methods: ['GET', 'POST']

admin_users_delete:
  path: /admin/Users/{id}
  controller: 'App\Controller\Admin\UsersController::delete'
  methods: ['POST']

admin_users_pdf:
  path: /admin/Users/pdf
  controller: 'App\Controller\Admin\UsersController::generatePdf'

app_forgot_password_request:
  path: /reset-password
  controller: 'App\Controller\ResetPasswordController::request'
  methods: ['GET', 'POST']

app_check_email:
  path: /reset-password/check-email
  controller: 'App\Controller\ResetPasswordController::checkEmail'
  methods: ['GET']

app_reset_password:
  path: /reset-password/reset/{token}
  controller: 'App\Controller\ResetPasswordController::reset'
  methods: ['GET', 'POST']

github_connect:
  path: '/connect/github'
  controller: 'App\Controller\SecurityController::connect'
  methods: ['GET', 'POST']

oauth_check:
  path: /oauth/check/{service}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController

user_chart:
  path: /user-chart
  controller: 'App\Controller\Admin\UsersController::userChart'
  methods: ['GET']

app_verify_email:
  path: '/verify-email/{token}'
  controller: 'App\Controller\VerificationController::verifyEmail'


